### ISSUE TITLE
Lizenzvertrag + Arten

### ISSUE THREAD

**Issue by Liro25** [JJandke/Berufsschule#1]
- beidseitiger Vertrag, indem der Inhaber bestimmter Produkte seine Rechte bezüglich des Produktes vollumfänglich oder nur zum Teil auf einen anderen übertragt
- darin wird geregelt, wie häufig, in welchem Umfang & wo die Produkte eingesetzt werden dürfen
- meist zeitlich begrenzt --> sobald Vertrag endet darf das Produkt nicht weiter genutzt werden

EULA
- Endbenutzer-Lizenzvereinbarung
- Lizenvereinbarung zwischen Hersteller einer Software & Endbenutzer
- Endbenutzer muss Vereinbarung vor Nutzung der Software zustimmen
- legt detailliert Rechte & Einschränkungen fest, die für die Nutzung der Software gelten
- WICHTIG ist der Begriff: "nutzen" --> keine Eigentumsrechte an der Software

OEM
- Original Equipment Manufacturer / Originalausrüstungshersteller / Erstausrüster
- rein lizenztechnisch ist Verkauf von OEM-Software nur in Verbindung mit Hardware erlaubt 
- Beispiel: Microsoft verkauft günsitgere OEM-Versionen von Windows 10 an Hersteller, die dann aber vertraglich die Software mit dem neuen PC ausliefern müssen

GNU
- GNU GPL --> GNU General Public License
- Copyright-Richtlinie für Open-Source-Software
- beschreibt wie Nutzer das Programm kopieren, modifizieren & weitergeben dürfen

**Comment by JJandke** [comment]
Wurde mit der Version um 14:51 eingepflegt. 
Bis die HTML-Version aktualisiert ist, kann's u.U. bis zu 5min dauern (ist automatisiert...)
