### ISSUE TITLE
GANTT-Diagramm Beispiel

### ISSUE THREAD

**Issue by Tom-Vogel** [JJandke/Berufsschule#17]
Hey ich habe jetzt extra aus der AP1 2023 Herbst die Aufgabe mit dem Gantt Diagramm am PC bearbeitet und auch Farblich markiert damit du es ggf. noch in den HedgDoc hinzufügen kannst.

Hier das Bild, ich hoffe es passt so:
![GANTT-Diagramm AP1 2023_Herbst](https://github.com/JJandke/Berufsschule/assets/160414965/de76dd50-61e8-4834-ba65-0c7f00b2cd45)

**Comment by JJandke** [comment]
Ist eingefügt, danke dir!
