### ISSUE TITLE
Cyberangriffsarten

### ISSUE THREAD

**Issue by Liro25** [JJandke/Berufsschule#2]
- Hacking
--> gezieltes Ausnutzen von Sicherheitslücken in den verwendeten Systemen oder das Umgehen bzw. Brechen von Sicherungsmechanismen um Zugriff zu erlangen
- -> Maßnahmen: Honeypots (täuschend echt aussehende Netzwerke mit gefälschtem Rechnern & Daten), Aufmerksamkeit eines möglichen Angreifers wird vom Produktivsystem weggelenkt

- Malware
--> Begriffskombination aus "malicious" (bösartig) & "software
--> vers. Arten von schädlicher Software
--> häufig Handlung des Benutzers erforderlich
--> Maßnahmen: Antivirussoftware, Firewall, Software-Update, Sicherheitsbewusstsein, E-Mail-Sicherheit, Datensicherung etc.
![image](https://github.com/JJandke/Berufsschule/assets/97919825/13046b0c-ced8-49c3-8b81-1c13fdf76240)
--> Ransomware: 
 = sperrt Zugriff auf Dateien oder Systeme
= Angreifer fordert Lösegeld für die Freigabe der gesperrten Daten
= kann Dateien verschlüsseln oder das gesamte System blockieren
--> Spyware:
= sammelt heimlich Informationen über Benutzeraktivitäten
= überwacht Tastatureingaben, Webseitenbesuche oder persönliche Daten
= Ziel ist oft das unbemerkte Sammeln von sensiblen Informationen
--> Adware:
= Advertising Malware (werbendes Schadprogramm)
= häufig über Drive-by-Downloads oder bewusster Downloads von kostenlosen Anwendungen auf das Gerät
= Ziel ist das Opfer zu einem Klick auf ungewollt eingespielte Werbung zu verleiten
--> Würmer:
= selbstverbreitende Programme ohne Hostdatei
= breiten sich eigenständig im Netzwerk aus
= nutzen Sicherheitslücken, um sich zu verbreiten
--> Trojaner:
= tarnen sich als legitime Software oder Dateien
= täuschen ihre wahre Absicht vor, um unbemerkt in ein System einzudringen
= nach Installation können sie schädliche Aktionen ausführen
--> Botnets:
= verbinden Computer zu riesigem Netzwerk
= Rechner wird für zwecke der Botmaster genutzt, die der User nicht bemerkt
= Computer werden ferngesteuert & wie willenlos (Zombie-PCs)

- Phising
--> Angreifer versuchen über gefälschte Webseiten, E-Mails, Nachrichten oder durch falsche Angaben am Telefon an vertrauenswürdige Daten zu gelangen
--> alternativ wird versucht, dass das Opfer schädliche Aktionen unter Anleitung des Angreifers durchführt
--> ist ein Beispiel für Social Engineering
--> Maßnahmen: Sensibilisierungs-Kampagnen, Schulungsmaßnahmen, Phising-Filter, Firewall & Sicherheitssoftware etc.

- Denial-of-Service (DoS)
--> konzentrierte Angriffe aus dem Internet, um einen bestimmten Dienst oder IT-System lahmzulegen bzw. zu überlasten
--> wenn die Angriffe von einer hohen Anzahl an Geräten verursacht werden, spricht man von einem "Distributed-Denial-of-Service" (DDoS) Angriff
--> Maßnahmen: umgehend Angreifer sperren oder blockieren (DoS), angegriffene Komponente vollständig vom Internet abschirmen bzw. abschalten (DDoS), Netzwerkmonitoring, Traffic Filtering, Redundanz, Begrenzung von Anfragen, Kapazitätsplanung etc.

**Comment by JJandke** [comment]
Wurde in der Version 15-02-2024 21:46 vollständig übernommen und teilw. angepasst. 
Gegenmaßnamen wurden etwas nach unten an passender Stelle verschoben.
