### ISSUE TITLE
Hypervisor Typ 1 & 2

### ISSUE THREAD

**Issue by Liro25** [JJandke/Berufsschule#3]
- Hypervisoren spielen eine zentrale Rolle bei der Servervirtualisierung und sind entscheidend für Cloud Computing
- Virtualisierung nutzt Software zur Simulation von physikalischen Ressourcen, wobei Hypervisoren virtuelle Maschinen erstellen und ausführen
- Typ 1-Hypervisoren (Bare Metal) werden direkt auf dem physischen Server installiert,
-  während Typ 2-Hypervisoren (gehostet) auf einem vorhandenen Betriebssystem laufen

**Comment by JJandke** [comment]
Danke dir.
Mit Version `16-02-2024 07:46` eingepflegt

**Comment by Liro25** [comment]
![image](https://github.com/JJandke/Berufsschule/assets/97919825/5f46cf39-5d2a-4e10-b95a-e80bbcc8c5e6)
