### ISSUE TITLE
Datenschutz: Grundsätze & Verbesserungen 

### ISSUE THREAD

**Issue by Liro25** [JJandke/Berufsschule#4]
- Datenminimierung 
= Personenbezogene Daten müssen dem Zweck angemessen & erheblich sowie auf das für die Zwecke der Verarbeitung notwendige Maß beschränkt sein
- Zweckbindung 
= Personenbezogene Daten müssen für festgelegte, eindeutige & legitime Zwecke erhoben werden & dürfen nicht in einer mit diesen Zwecken nicht zu vereinbarenden Weise weiterverarbeitet werden
- Verbot mit Erlaubnisvorbehalt 
=Generell besteht ein Verbot der Nutzung & Verarbeitung von personenbezogenen Daten
= die Daten dürfen nur genutzt &/oder verarbeitet werden,
wenn eine Erlaubnis erteilt wurde (z. B. durch Bestätigung
der betroffenen Person oder weil die Verarbeitung zur Vertrags-
erfüllung notwendig ist
- Datenrichtigkeit 
= Daten müssen sowohl sachlich als auch inhaltlich korrekt & aktuell sein
- Rechtmäßigkeit & Transparenz
= Die erhobenen Daten müssen nachvollziehbar auf &eine rechtmäßige Weise verarbeitet werden
- Datenintegrität/-vertraulichkeit & -sicherheit 
= Durch technische & organisatorische Maßnahmen (TOMs) ist sicherzustellen, das eine angemessene Sicherheit,
Vertraulichkeit & Integrität der Daten gewährleistet wird
- Speicherbegrenzung
= Personenbezogene Daten müssen in einer Form
gespeichert werden, die die Identifizierung der
betroffenen Personen nur so lange ermöglicht, wie es
für die Zwecke, für die Sie verarbeitet werden, erfor-
derlich ist

**Comment by JJandke** [comment]
Danke dir!!!
Mit Version um 15-02-2024 17:58 eingebracht
