### ISSUE TITLE
White- & Black-Box-Test

### ISSUE THREAD

**Issue by Liro25** [JJandke/Berufsschule#5]
- Methoden des Softwaretestings
- Black-Box-Test:
--> Tester testet ohne Kenntnisse über die innere Funktionsweise bzw. Implementierung des Systems das Verhalten bzw. die Funktionen testet
- White-Box-Test:
--> richtet Blick auf den implementierten Algorithmus & überprüft die Korrektheit des Quellcodes

**Comment by JJandke** [comment]
Mit Version `16-02-2024 08:47 `eingepflegt
