### ISSUE TITLE
Testverfahren

### ISSUE THREAD

**Issue by Liro25** [JJandke/Berufsschule#6]
- **Black-Box-Test:**
  - Testet die Funktionalität einer Software, ohne Kenntnisse über die interne Struktur.
  - Fokus auf den Input und die erwartete Ausgabe.

- **White-Box-Test:**
  - Prüft die interne Struktur einer Software, einschließlich des Codes.
  - Ziele sind Codeabdeckung, Pfadüberdeckung und Strukturanalyse.

- **Komponententest:**
  - Einzelne Softwarekomponenten werden isoliert getestet.
  - Ziel ist die Überprüfung der Korrektheit und Funktionalität jeder Komponente.

- **Unittest:**
  - Testet einzelne Einheiten (z. B. Funktionen oder Methoden) des Quellcodes.
  - Fokussiert auf die Isolation und Überprüfung kleiner Codeabschnitte.

- **Modultest:**
  - Prüft, ob Module oder Teile eines Systems korrekt zusammenarbeiten.
  - Umfasst mehrere Einheiten, die eine bestimmte Funktionalität bieten.

- **Integrationstest:**
  - Überprüft die Interaktion zwischen verschiedenen Komponenten oder Modulen.
  - Ziel ist es, Fehler in der Kommunikation und Zusammenarbeit aufzudecken.

- **Systemtest:**
  - Testet das gesamte System als Ganzes.
  - Überprüft, ob alle Komponenten integriert funktionieren und die Anforderungen erfüllen.

- **Abnahmetest:**
  - Kunden oder Benutzer führen Tests durch, um sicherzustellen, dass die Software ihren Anforderungen entspricht.
  - Ziel ist die Bestätigung der Benutzerfreundlichkeit und Erfüllung der Anforderungen.

- **Lasttest:**
  - Simuliert eine hohe Belastung, um die Leistungsfähigkeit eines Systems zu überprüfen.
  - Identifiziert Engpässe und Probleme unter Stressbedingungen.

**Comment by JJandke** [comment]
Dankööö, ist mit Version `16-02-2024 08:53` dabei ;)
