### ISSUE TITLE
Ökonomische Ziele eines Unternehmens

### ISSUE THREAD

**Issue by Liro25** [JJandke/Berufsschule#7]
- **Ertragsziele:**
  - alles was mit den begriffen Umsatz, Gewinn & Kapital zusammenhängt

- **Marktziele:**
  - definiert der Unternehmer selbst, indem er festlegt, welchen gewünschten Marktanteil er haben möchte bzw. welche Steigerung des Marktanteils er für sich in Aussicht stellt

- **Leistungsziel:**
  - gewisse Qualitätsstandards
  - Sicherstellung der Arbeitsplätze

**Comment by JJandke** [comment]
An welche Stelle willst du das haben?
Gehört das zu einem bestimmten Thema oder einfach so als Ergänzug?

**Comment by JJandke** [comment]
Mit Version  `16-02-2024 10:33` eingefügt.
